import http from 'http';
import { readFile, stat } from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { fetchPitcherStrikeoutSlate } from './odds.js';
const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename),publicDir=path.join(__dirname,'public'),PORT=process.env.PORT||3000,MLB_BASE='https://statsapi.mlb.com/api/v1';
const MIME_TYPES={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8'};
const sendJson=(res,s,d)=>{res.writeHead(s,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(d));};
const round=(v,d=2)=>v==null||Number.isNaN(v)?null:Number(v.toFixed(d));
function implied(o){const n=Number(o);if(!Number.isFinite(n)||!n)return null;return n>0?100/(n+100):Math.abs(n)/(Math.abs(n)+100);}
function ev(p,o,stake=100){const n=Number(o);if(!Number.isFinite(p)||!Number.isFinite(n))return null;const win=n>0?stake*n/100:stake*100/Math.abs(n);return p*win-(1-p)*stake;}
function erf(x){const s=x>=0?1:-1,a1=.254829592,a2=-.284496736,a3=1.421413741,a4=-1.453152027,a5=1.061405429,p=.3275911,t=1/(1+p*Math.abs(x));return s*(1-(((((a5*t+a4)*t+a3)*t+a2)*t+a1)*t*Math.exp(-x*x)));}
const cdf=(x,m,s)=>s<=0?(x<m?0:1):.5*(1+erf((x-m)/(s*Math.sqrt(2))));
const overProb=(line,m,s)=>1-cdf(Math.floor(line)+.5,m,s);
async function mlb(endpoint){const r=await fetch(`${MLB_BASE}${endpoint}`,{headers:{'User-Agent':'mlb-k-prop-dashboard/2.0'}});if(!r.ok)throw new Error(`MLB API ${r.status}`);return r.json();}
async function pitcher(name){const d=await mlb(`/people/search?names=${encodeURIComponent(name)}&sportId=1`),p=(d.people||[]).find(x=>String(x.primaryPosition?.code)==='1')||d.people?.[0];if(!p)throw new Error(`No MLB pitcher found for ${name}`);return p;}
async function matchup(id,date){const d=await mlb(`/schedule?sportId=1&date=${date}&hydrate=probablePitcher,team`);for(const day of d.dates||[])for(const g of day.games||[]){if(g.teams?.home?.probablePitcher?.id===id)return{opp:g.teams.away.team,team:g.teams.home.team,venue:g.venue?.name};if(g.teams?.away?.probablePitcher?.id===id)return{opp:g.teams.home.team,team:g.teams.away.team,venue:g.venue?.name};}return null;}
async function gameLog(id,season){const d=await mlb(`/people/${id}/stats?stats=gameLog&group=pitching&season=${season}`);return(d.stats?.[0]?.splits||[]).map(s=>({date:s.date,strikeOuts:Number(s.stat?.strikeOuts||0),inningsPitched:Number(s.stat?.inningsPitched||0)}));}
async function seasonStats(id,season){const d=await mlb(`/people/${id}/stats?stats=season&group=pitching&season=${season}`),s=d.stats?.[0]?.splits?.[0]?.stat;if(!s)throw new Error('No season pitching stats');return{starts:Number(s.gamesStarted||0),ip:Number(s.inningsPitched||0),ks:Number(s.strikeOuts||0),k9:Number(s.strikeOutsPer9Inn||0),era:Number(s.era||0),whip:Number(s.whip||0)};}
async function teamStats(id,season){const d=await mlb(`/teams/${id}/stats?stats=season&group=hitting&season=${season}`),s=d.stats?.[0]?.splits?.[0]?.stat;if(!s)return null;const pa=Number(s.plateAppearances||0);return{kr:pa?Number(s.strikeOuts||0)/pa:null};}
const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;const sd=a=>{const m=avg(a);return Math.sqrt(avg(a.map(x=>(x-m)**2)));};
async function analyzePitcher({name,line,overOdds,underOdds,date,season,inningsOverride}){const p=await pitcher(name),[m,s,g]=await Promise.all([matchup(p.id,date),seasonStats(p.id,season),gameLog(p.id,season)]);if(!g.length)throw new Error(`No ${season} game log for ${p.fullName}`);const l5=g.slice(-5),l10=g.slice(-10),seasonIp=s.starts?s.ip/s.starts:0,recentIp=avg(l5.map(x=>x.inningsPitched)),projIp=Number(inningsOverride)>0?Number(inningsOverride):(.65*recentIp+.35*seasonIp);let opp=null,adj=1;if(m?.opp?.id){opp=await teamStats(m.opp.id,season);if(opp?.kr)adj=Math.max(.85,Math.min(1.15,opp.kr/.225));}const proj=(s.ip?s.ks/s.ip:0)*projIp*adj,std=Math.max(1.15,sd(l10.map(x=>x.strikeOuts))),po=overProb(Number(line),proj,std),pu=1-po,io=implied(overOdds),iu=implied(underOdds),eo=overOdds?ev(po,Number(overOdds)):null,eu=underOdds?ev(pu,Number(underOdds)):null,edgeO=io==null?null:po-io,edgeU=iu==null?null:pu-iu;let bestBet='Pass';if(eo!=null&&eo>0&&(eu==null||eo>eu))bestBet='Over';if(eu!=null&&eu>0&&(eo==null||eu>eo))bestBet='Under';return{pitcher:{id:p.id,name:p.fullName,team:m?.team?.name||null},matchup:{date,opponent:m?.opp?.name||null,venue:m?.venue||null},input:{line:Number(line),overOdds:overOdds==null?null:Number(overOdds),underOdds:underOdds==null?null:Number(underOdds),overProb:round(po*100,1),underProb:round(pu*100,1),evOver:round(eo),evUnder:round(eu),edgeOver:round(edgeO*100,1),edgeUnder:round(edgeU*100,1),bestBet},stats:{seasonK9:round(s.k9),last5AvgKs:round(avg(l5.map(x=>x.strikeOuts))),last10HitRate:round(l10.filter(x=>x.strikeOuts>Number(line)).length/l10.length,3),projectedInnings:round(projIp),opponentStrikeoutRate:round(opp?.kr,3),projectedKs:round(proj),ksStdDevLast10:round(std)},recentGames:[...l10].reverse()};}
async function analyzeInputs(inputs,date,season){const results=[];for(const input of inputs){try{results.push({ok:true,result:await analyzePitcher({...input,date,season}),market:input.market||null});}catch(e){results.push({ok:false,input,error:e.message});}}return results;}
async function serveStatic(req,res){let pn=new URL(req.url,`http://localhost:${PORT}`).pathname;if(pn==='/')pn='/index.html';const fp=path.join(publicDir,pn);if(!fp.startsWith(publicDir)){res.writeHead(403);return res.end('Forbidden');}try{const st=await stat(fp);if(!st.isFile())throw 0;const c=await readFile(fp);res.writeHead(200,{'Content-Type':MIME_TYPES[path.extname(fp)]||'application/octet-stream'});res.end(c);}catch{res.writeHead(404);res.end('Not found');}}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,`http://localhost:${PORT}`);if(u.pathname==='/api/daily-slate'&&req.method==='GET'){const date=u.searchParams.get('date')||new Date().toISOString().slice(0,10),season=Number(u.searchParams.get('season'))||new Date().getFullYear(),slate=await fetchPitcherStrikeoutSlate(date),inputs=slate.pitchers.map(m=>({name:m.name,line:m.line,overOdds:m.overOdds,underOdds:m.underOdds,market:m})),results=await analyzeInputs(inputs,date,season);return sendJson(res,200,{...slate,results});}if(u.pathname==='/api/analyze-batch'&&req.method==='POST'){let body='';req.on('data',c=>body+=c);req.on('end',async()=>{try{const p=JSON.parse(body||'{}'),date=p.date||new Date().toISOString().slice(0,10),season=p.season||new Date().getFullYear();sendJson(res,200,{results:await analyzeInputs(Array.isArray(p.inputs)?p.inputs:[],date,season)});}catch(e){sendJson(res,400,{error:e.message});}});return;}await serveStatic(req,res);}catch(e){sendJson(res,500,{error:e.message||'Internal server error'});}});server.listen(PORT,()=>console.log(`MLB K Edge Dashboard on ${PORT}`));